### ISSUE TITLE
Needs license

### ISSUE THREAD

**Issue by edmw** [federicosintucci/Volumio_ios#2]
Hi,
first, I found this to be a great little app.

I've just submitted a pull request which solves a bug I found. I'm willing to contribute even more, but to do so I have to know the license terms under which you are going to distribute this code.

**Comment by federicosintucci** [comment]
Hi Michael, 
thanks for your work!

I'll distribuite the app under this agreement https://volumio.org/licence-and-credits/.
It's a GNU GPL like the Volumio's main project.

**Comment by edmw** [comment]
Ok, works for me. Maybe you want to add a License file to the project. I'll pull a refactoring next and will then start to work on the app’s localization.

**Comment by federicosintucci** [comment]
Sound great! I've just pushed some rusty code to make it work, but it must be written in a proper way ;) I'll add the license right now.
