### ISSUE TITLE
Notices from PlaybackViewController interfere with other notices

### ISSUE THREAD

**Issue by edmw** [federicosintucci/Volumio_ios#4]
Hi,
the observers for Volumio’s events in PlaybackViewController are registered in viewDidLoad (and are not removed until deinit). Is this on purpose?
 
Calls to SwiftNotice from PlaybackViewController as reaction on events from Volumio are interfering with notices from other view controllers.

To reproduce go to 'Browse' and tap 'Play all'. The notice for 'xyz added to queue' will disappear immediately because clearAllNotice is called in PlaybackViewController.getCurrentTrack.

**Comment by federicosintucci** [comment]
I know about that behaviour, i have to check why i choose to leave the observers active even while not on that view. Probably because at first i wanted to notify the user about the playing track on change...but i'm not so sure about it. I'll check this evening ;)

**Comment by edmw** [comment]
Changed with #14. Should be ok for now.

**Comment by edmw** [comment]
Please open if there are any issues again.
