### ISSUE TITLE
App is not finding a player

### ISSUE THREAD

**Issue by joeranriesszal** [federicosintucci/Volumio_ios#8]
Hi,

tried the app today on my iPhone 6 running the latest version of iOS. After starting the app the dialogue asks me to select a player, but none is showing up. After discarding the screen, switching to the settings and launching web UI works fine in the browser. Would be nice to fix that issue and/or make it possible to connect to a specific IP as I assume there is a problem with finding the player on the network.

Best,
Jöran

**Comment by federicosintucci** [comment]
Hi Jöran,
did you build the development branch or the app from the store?
We know the released one works only on default configurations, i just submitted a new build. Hope will be released before the end of the week ;)

**Comment by joeranriesszal** [comment]
Hej,
I used the app from the store and in my personal network at home it just worked fine. In my company network though I was not able to find it. You are right, might be the problem with default configurations. I will close the issue as the problem does not occur in my normal environment.
